# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: 'Default'  

variables:
  pythonVersion: '3.12'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python manage.py check
      python manage.py collectstatic --noinput
    displayName: 'Django system checks'
    continueOnError: true

  - script: |
      python manage.py test
    displayName: 'Run Django tests'
